version: '3'
services:
  php_app_new:
    build: ./php_app
    ports:
      - "80"
    healthcheck:
      test: socat - TCP4:localhost:80 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
    restart: unless-stopped
  flask_app_new:
    build: ./flask_app
    ports:
      - "4012:5000"
    links:
      - php_app_new
    healthcheck:
      test: socat - TCP4:localhost:5000 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
    restart: unless-stopped
