version: '3.3'

services:

  web:
    build:
      context: ./challenge
      dockerfile: Dockerfile
    ports:
      - '4003:3000'
    healthcheck:
      test: socat - TCP4:localhost:3000 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5