version: '3.3'

services:    
  flask_app_jack:
    build: ./flask_app
    environment:
      - flag=nexus{00ps1Es_d1dNt_MEan_t0_C0nfuse_y0U_tw1c3}
    healthcheck:
      test: socat - TCP4:localhost:5000 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
    restart: unless-stopped
  node_app_jack:
    build: ./node_app
    ports:
      - '4050:3000'
    depends_on:
      - flask_app_jack
    healthcheck:
      test: socat - TCP4:localhost:3000 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
    restart: unless-stopped
    
