version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4005:80'
    healthcheck:
      test: curl -I --fail http://localhost/ || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
