version: "3.8"
services:
  server:
    build: .
    ports:
      - 4100:3000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: socat - TCP4:localhost:80 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
